Repository TechUni2020/TechUni-hp, pull requests merged in 2024-09, with the labels that each got.

#59 [fix] ホームのスポンサーロゴスライダーの動作不具合
  src/components/Home/SponserLogoSlider.jsx
  src/components/Home/slider.jsx
  src/components/Sponsor/SponsorLogo.jsx
  src/style.css
Labels: Type: Bugfix

#66 Release: 見た目関係の不具合修正
  src/assets/Sponsor/TripleFour.png
  src/components/Footer.jsx
  src/components/Home/SponserLogoSlider.jsx
  src/components/Home/slider.jsx
  src/components/Navbar.jsx
  src/components/Sponsor/Sponsor.jsx
  src/components/Sponsor/SponsorLogo.jsx
  src/style.css
Labels: Type: Bugfix, Type: Improvement

#69 [fix] モバイル時のnavbar動作の不具合を修正
  src/components/Navbar.jsx
Labels: Type: Bugfix

#70 [change] 連絡先用メール関連のデザイン調整
  src/components/Footer.jsx
  src/components/Home/Home2.jsx
Labels: Type: Improvement, Type: Content-Update

#71 Release: HomeとNavbar, Fotterのデザイン調整
  src/assets/TechUni.png
  src/assets/TechUni.svg
  src/components/About/About.jsx
  src/components/Footer.jsx
  src/components/Home/Home2.jsx
  src/components/Navbar.jsx
Labels: Type: Bugfix, Type: Improvement, Type: Content-Update
